



services:
  php-fpm:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password4
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network

  nginx:
    image: nginx:1.26.1
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
